/**
 * GitLab错误码常量
 * 定义GitLab集成功能中使用的错误码
 */

/**
 * GitLab错误码枚举
 */
export enum GitLabErrorCodes {
  // 实例相关错误
  INSTANCE_NOT_FOUND = 'GITLAB_INSTANCE_NOT_FOUND',
  INSTANCE_ALREADY_EXISTS = 'GITLAB_INSTANCE_ALREADY_EXISTS',
  INSTANCE_INVALID_CONFIG = 'GITLAB_INSTANCE_INVALID_CONFIG',
  INSTANCE_CONNECTION_FAILED = 'GITLAB_INSTANCE_CONNECTION_FAILED',
  INSTANCE_AUTHENTICATION_FAILED = 'GITLAB_INSTANCE_AUTHENTICATION_FAILED',

  // API相关错误
  API_ERROR = 'GITLAB_API_ERROR',
  API_CONNECTION_FAILED = 'GITLAB_API_CONNECTION_FAILED',
  API_AUTHENTICATION_FAILED = 'GITLAB_API_AUTHENTICATION_FAILED',
  API_RATE_LIMITED = 'GITLAB_API_RATE_LIMITED',
  API_TIMEOUT = 'GITLAB_API_TIMEOUT',
  API_INVALID_RESPONSE = 'GITLAB_API_INVALID_RESPONSE',

  // 同步相关错误
  SYNC_ERROR = 'GITLAB_SYNC_ERROR',
  SYNC_IN_PROGRESS = 'GITLAB_SYNC_IN_PROGRESS',
  SYNC_FAILED = 'GITLAB_SYNC_FAILED',
  SYNC_TIMEOUT = 'GITLAB_SYNC_TIMEOUT',
  SYNC_INVALID_CONFIG = 'GITLAB_SYNC_INVALID_CONFIG',
  SYNC_INVALID_DATA = 'GITLAB_SYNC_INVALID_DATA',

  // 验证相关错误
  VALIDATION_ERROR = 'GITLAB_VALIDATION_ERROR',
  FIELD_VALIDATION_ERROR = 'GITLAB_FIELD_VALIDATION_ERROR',
  REQUIRED_FIELD_MISSING = 'GITLAB_REQUIRED_FIELD_MISSING',
  FIELD_FORMAT_INVALID = 'GITLAB_FIELD_FORMAT_INVALID',
  FIELD_LENGTH_EXCEEDED = 'GITLAB_FIELD_LENGTH_EXCEEDED',
  FIELD_VALUE_OUT_OF_RANGE = 'GITLAB_FIELD_VALUE_OUT_OF_RANGE',

  // 权限相关错误
  PERMISSION_ERROR = 'GITLAB_PERMISSION_ERROR',
  PERMISSION_DENIED = 'GITLAB_PERMISSION_DENIED',
  INSUFFICIENT_PERMISSIONS = 'GITLAB_INSUFFICIENT_PERMISSIONS',
  PERMISSION_CONFIG_INVALID = 'GITLAB_PERMISSION_CONFIG_INVALID',
  PERMISSION_RESOURCE_NOT_FOUND = 'GITLAB_PERMISSION_RESOURCE_NOT_FOUND',
  PERMISSION_USER_NOT_FOUND = 'GITLAB_PERMISSION_USER_NOT_FOUND',

  // 项目映射相关错误
  PROJECT_MAPPING_NOT_FOUND = 'GITLAB_PROJECT_MAPPING_NOT_FOUND',
  PROJECT_MAPPING_ALREADY_EXISTS = 'GITLAB_PROJECT_MAPPING_ALREADY_EXISTS',
  PROJECT_MAPPING_INVALID = 'GITLAB_PROJECT_MAPPING_INVALID',

  // 用户映射相关错误
  USER_MAPPING_NOT_FOUND = 'GITLAB_USER_MAPPING_NOT_FOUND',
  USER_MAPPING_ALREADY_EXISTS = 'GITLAB_USER_MAPPING_ALREADY_EXISTS',
  USER_MAPPING_INVALID = 'GITLAB_USER_MAPPING_INVALID',

  // 事件相关错误
  EVENT_PROCESSING_FAILED = 'GITLAB_EVENT_PROCESSING_FAILED',
  EVENT_VALIDATION_FAILED = 'GITLAB_EVENT_VALIDATION_FAILED',
  EVENT_DUPLICATE = 'GITLAB_EVENT_DUPLICATE',

  // 缓存相关错误
  CACHE_ERROR = 'GITLAB_CACHE_ERROR',
  CACHE_CONNECTION_FAILED = 'GITLAB_CACHE_CONNECTION_FAILED',
  CACHE_OPERATION_FAILED = 'GITLAB_CACHE_OPERATION_FAILED',

  // 配置相关错误
  CONFIG_ERROR = 'GITLAB_CONFIG_ERROR',
  CONFIG_VALIDATION_FAILED = 'GITLAB_CONFIG_VALIDATION_FAILED',
  CONFIG_NOT_FOUND = 'GITLAB_CONFIG_NOT_FOUND',

  // 通用错误
  INTERNAL_ERROR = 'GITLAB_INTERNAL_ERROR',
  EXTERNAL_SERVICE_ERROR = 'GITLAB_EXTERNAL_SERVICE_ERROR',
  NETWORK_ERROR = 'GITLAB_NETWORK_ERROR',
  TIMEOUT_ERROR = 'GITLAB_TIMEOUT_ERROR',
}

/**
 * 错误码描述映射
 */
export const GitLabErrorDescriptions: Record<GitLabErrorCodes, string> = {
  // 实例相关错误描述
  [GitLabErrorCodes.INSTANCE_NOT_FOUND]: 'GitLab实例未找到',
  [GitLabErrorCodes.INSTANCE_ALREADY_EXISTS]: 'GitLab实例已存在',
  [GitLabErrorCodes.INSTANCE_INVALID_CONFIG]: 'GitLab实例配置无效',
  [GitLabErrorCodes.INSTANCE_CONNECTION_FAILED]: 'GitLab实例连接失败',
  [GitLabErrorCodes.INSTANCE_AUTHENTICATION_FAILED]: 'GitLab实例认证失败',

  // API相关错误描述
  [GitLabErrorCodes.API_ERROR]: 'GitLab API错误',
  [GitLabErrorCodes.API_CONNECTION_FAILED]: 'GitLab API连接失败',
  [GitLabErrorCodes.API_AUTHENTICATION_FAILED]: 'GitLab API认证失败',
  [GitLabErrorCodes.API_RATE_LIMITED]: 'GitLab API请求被限流',
  [GitLabErrorCodes.API_TIMEOUT]: 'GitLab API请求超时',
  [GitLabErrorCodes.API_INVALID_RESPONSE]: 'GitLab API响应无效',

  // 同步相关错误描述
  [GitLabErrorCodes.SYNC_ERROR]: 'GitLab同步错误',
  [GitLabErrorCodes.SYNC_IN_PROGRESS]: 'GitLab同步正在进行中',
  [GitLabErrorCodes.SYNC_FAILED]: 'GitLab同步失败',
  [GitLabErrorCodes.SYNC_TIMEOUT]: 'GitLab同步超时',
  [GitLabErrorCodes.SYNC_INVALID_CONFIG]: 'GitLab同步配置无效',
  [GitLabErrorCodes.SYNC_INVALID_DATA]: 'GitLab同步数据无效',

  // 验证相关错误描述
  [GitLabErrorCodes.VALIDATION_ERROR]: 'GitLab验证错误',
  [GitLabErrorCodes.FIELD_VALIDATION_ERROR]: 'GitLab字段验证错误',
  [GitLabErrorCodes.REQUIRED_FIELD_MISSING]: 'GitLab必填字段缺失',
  [GitLabErrorCodes.FIELD_FORMAT_INVALID]: 'GitLab字段格式无效',
  [GitLabErrorCodes.FIELD_LENGTH_EXCEEDED]: 'GitLab字段长度超出限制',
  [GitLabErrorCodes.FIELD_VALUE_OUT_OF_RANGE]: 'GitLab字段值超出范围',

  // 权限相关错误描述
  [GitLabErrorCodes.PERMISSION_ERROR]: 'GitLab权限错误',
  [GitLabErrorCodes.PERMISSION_DENIED]: 'GitLab权限被拒绝',
  [GitLabErrorCodes.INSUFFICIENT_PERMISSIONS]: 'GitLab权限不足',
  [GitLabErrorCodes.PERMISSION_CONFIG_INVALID]: 'GitLab权限配置无效',
  [GitLabErrorCodes.PERMISSION_RESOURCE_NOT_FOUND]: 'GitLab权限资源不存在',
  [GitLabErrorCodes.PERMISSION_USER_NOT_FOUND]: 'GitLab权限用户不存在',

  // 项目映射相关错误描述
  [GitLabErrorCodes.PROJECT_MAPPING_NOT_FOUND]: 'GitLab项目映射未找到',
  [GitLabErrorCodes.PROJECT_MAPPING_ALREADY_EXISTS]: 'GitLab项目映射已存在',
  [GitLabErrorCodes.PROJECT_MAPPING_INVALID]: 'GitLab项目映射无效',

  // 用户映射相关错误描述
  [GitLabErrorCodes.USER_MAPPING_NOT_FOUND]: 'GitLab用户映射未找到',
  [GitLabErrorCodes.USER_MAPPING_ALREADY_EXISTS]: 'GitLab用户映射已存在',
  [GitLabErrorCodes.USER_MAPPING_INVALID]: 'GitLab用户映射无效',

  // 事件相关错误描述
  [GitLabErrorCodes.EVENT_PROCESSING_FAILED]: 'GitLab事件处理失败',
  [GitLabErrorCodes.EVENT_VALIDATION_FAILED]: 'GitLab事件验证失败',
  [GitLabErrorCodes.EVENT_DUPLICATE]: 'GitLab事件重复',

  // 缓存相关错误描述
  [GitLabErrorCodes.CACHE_ERROR]: 'GitLab缓存错误',
  [GitLabErrorCodes.CACHE_CONNECTION_FAILED]: 'GitLab缓存连接失败',
  [GitLabErrorCodes.CACHE_OPERATION_FAILED]: 'GitLab缓存操作失败',

  // 配置相关错误描述
  [GitLabErrorCodes.CONFIG_ERROR]: 'GitLab配置错误',
  [GitLabErrorCodes.CONFIG_VALIDATION_FAILED]: 'GitLab配置验证失败',
  [GitLabErrorCodes.CONFIG_NOT_FOUND]: 'GitLab配置未找到',

  // 通用错误描述
  [GitLabErrorCodes.INTERNAL_ERROR]: 'GitLab内部错误',
  [GitLabErrorCodes.EXTERNAL_SERVICE_ERROR]: 'GitLab外部服务错误',
  [GitLabErrorCodes.NETWORK_ERROR]: 'GitLab网络错误',
  [GitLabErrorCodes.TIMEOUT_ERROR]: 'GitLab超时错误',
};
